USE sakila;

-- Using the following query, modify it so that it only displays average durations that are between 115.0 to 121.50. Also, give an alias (nickname) to the column generated by AVG(length) in order to make the query more readable. Finish by sorting the results in descending order;

-- SELECT rating, AVG(length)
-- FROM sakila.film
-- GROUP BY rating;
    
SELECT rating, AVG(length) AS average_length FROM film
GROUP BY rating
HAVING average_length BETWEEN 115.0 and 121.50;
-- Dúvida~ não consigo usar alias p/ comparação. Tem algum jeito?

-- Using the following query, display only the total replacement cost values ​​that are above $3950.50. Give an alias that makes sense to SUM(replacement_cost), in a way that makes the query more readable. Finish by sorting the results in ascending order;

-- SELECT rating, SUM(replacement_cost)
-- FROM sakila.film
-- GROUP by rating;

SELECT rating, SUM(replacement_cost) AS 'total replacement cost' FROM film
GROUP BY rating
HAVING SUM(replacement_cost) > 3950.5;